#!/bin/sh

#If already done quit!

#New start up 2014-01-31

echo "\t\tInstalling new startup script!"

#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCRIPT=$(readlink -f $0)
DIR=`dirname $SCRIPT`

#echo $DIR

STARTUP_SCRIPT=$DIR/../tools/elvis
OLD_SCRIPT=/etc/init.d/wltl

cp "$STARTUP_SCRIPT" /etc/init.d/


if [ -e "$OLD_SCRIPT" ];
then
	echo "\t\tDeleting old startup script!"
	rm "$OLD_SCRIPT"
fi

sudo update-rc.d elvis defaults
sudo update-rc.d elvis enable


echo "\t\tDone!"



