#!/bin/bash

echo "Input the kit number:"

read KitN

OLD="EnergyKitX"
NEW="EnergyKit$KitN"

echo "Setting the name to $NEW"

file1="/etc/hosts"
file2="/etc/hostname"

sed -i "s/$OLD/$NEW/g" "$file1"
sed -i "s/$OLD/$NEW/g" "$file2"

#MY_PATH="`dirname \"$0\"`"

#$MY_PATH/../updates/UpdateStartupScript

#service elvis start
