#!/bin/sh
# /etc/init.d/elvis

### BEGIN INIT INFO
# Provides:          elvis
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: (e)lVis startup script
# Description:       (e)lVis startup script
### END INIT INFO

ELVIS=/home/pi/git/elvis
NODE=/home/pi/node/0/bin/node
NODE_PATH=/home/pi/node/0/lib/node_modules:$ELVIS/node_modules

case "$1" in
  start)
    echo "Starting elvis"
    cd $ELVIS/server && python elvis_server.py &
    export NODE_PATH=$NODE_PATH
    echo $NODE_PATH
    cd $ELVIS/client && $NODE client.js &
    ;;
  stop)
    echo "Stopping elvis"
    killall python
    killall node
    ;;
  *)
    echo "Usage: service elvis (start|stop)"
    exit 1
    ;;
esac

exit 0
