#!/bin/sh
# /etc/init.d/wltl

### BEGIN INIT INFO
# Provides:          wltl
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Watt-Lite-Twist-Lite startup script
# Description:       Watt-Lite-Twist-Lite startup script
### END INIT INFO

WLTL=/home/pi/git/watt-lite-twist-lite
ELVIS=/home/pi/git/elvis

NODE=/home/pi/node/0/bin/node
NODE_PATH=/home/pi/node/0/lib/node_modules:$WLTL/node_modules

case "$1" in
  start)
    echo "Starting Elvis"
    
    #New or old path
    if [ -d "$ELVIS" ]; then
      INSTALLATION_PATH=$ELVIS
    else
      INSTALLATION_PATH=$WLTL
    fi
    
    clear
    
    echo "Starting sensor server..."
    
    cd $INSTALLATION_PATH/server 
    python elvis_server.py > /dev/null &
    export NODE_PATH=$NODE_PATH
    echo $NODE_PATH
    
    echo "Waiting for server to start up..."
    
    cd $INSTALLATION_PATH/client && $NODE client.js > /dev/null &
    
    #Wait and then check that the process is running. 
    for I in 1 2 3 4 5
    do
        sleep 5
        if ! [ -z "$(pgrep client.js -f)" ]
        then
          #Restart again. 
          cd $INSTALLATION_PATH/client && $NODE client.js > /dev/null &
        else
          #Everything seems ok!  
          break
        fi
        
    done
    
    ;;
  stop)
    echo "Stopping wltl"
    killall python
    killall node
    ;;
  *)
    echo "Usage: service elvis (start|stop)"
    exit 1
    ;;
esac

exit 0
